### ISSUE TITLE
Help with courier

### ISSUE THREAD

**Issue by funkyfela** [ctrlaltdylan/courier#2]
Hello. Couldn't find a comprehensive tutorial on how to use courier on my web application. can you help with guide? what i tried didnt work.

thank you

**Comment by funkyfela** [comment]
This is what i did and it did not work. can u help out pls
thanks
<?php

require 'Courier.php';

if(isset($_POST['submit'])){
    $recipient = $_POST['recipient'];
    $msg = $_POST['msg'];

$courier = new Courier\Courier;

//$courier->setRecipient('867530999')->setBody('Hello World')->send();
$courier->setRecipient($recipient)->setBody($msg)->send();

}

?>

<form method="post" action="">
<label>Recipient</label><br>
<input type="text" name="recipient" required><br>
<label>Message</label><br>
<textarea name="msg" required></textarea><br>
<input name="submit" type="submit" value="SUBMIT">
</form>

**Comment by ctrlaltdylan** [comment]
Hi, this package is designed to be installed with composer. I don't think you can `require` and have the namespace `Courier\Courier` work. I updated the installation instructions but you need to install composer. Then with composer you can add packages to your application.

`composer require ctrlaltdylan/courier`
