### ISSUE TITLE
International support

### ISSUE THREAD

**Issue by reense** [ctrlaltdylan/courier#3]
Hi,
The base url is currently set to http://textbelt.com/text.
However, for sending international texts you should be using /intl.
Is there a possibility to build a ->toInternational() option or something like that?

**Comment by ctrlaltdylan** [comment]
That's a good idea, perhaps it should be an option you can set in the constructor as well.

**Comment by ctrlaltdylan** [comment]
Added international support to v1.1, master up to date with tests and documentation.
